### ISSUE TITLE
I have this problem

### ISSUE THREAD

**Issue by davesuriano** [singaCapital/BLE-Beacon-Scanner#10]
Traceback (most recent call last):
  File "BeaconScanner.py", line 3, in <module>
    import ScanUtility
  File "/home/pi/Desktop/BLE-Beacon-Scanner-master/ScanUtility.py", line 6, in <module>
    import bluetooth._bluetooth as bluez
  File "/usr/local/lib/python2.7/dist-packages/bluetooth/__init__.py", line 282, in <module>
    """
AttributeError: attribute '__doc__' of 'instancemethod' objects is not writable

**Comment by aarushg22** [comment]
#5
